# Generated by Django 5.2.7 on 2025-11-04 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDEPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide_name', models.CharField(choices=[('vscode', 'Visual Studio Code'), ('pycharm', 'PyCharm'), ('intellij', 'IntelliJ IDEA'), ('vim', 'Vim'), ('neovim', 'Neovim'), ('sublime', 'Sublime Text'), ('atom', 'Atom'), ('eclipse', 'Eclipse'), ('other', 'Other IDE')], max_length=20)),
                ('plugin_version', models.CharField(max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDEEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('code_review', 'Code Review Requested'), ('test_generation', 'Test Generation Requested'), ('test_execution', 'Test Execution Requested'), ('code_fix', 'Code Fix Applied'), ('security_scan', 'Security Scan Requested')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide_integration.ideplugin')),
            ],
        ),
        migrations.CreateModel(
            name='IDEConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_token', models.CharField(max_length=100, unique=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ide_integration.ideplugin')),
            ],
        ),
    ]
